---
- name: 创建目录
  file:
    path: '{{ item }}'
    state: directory
    mode: '0755'
  loop:
    - /etc/cni/net.d
    - /opt/cni/bin
    - /etc/kubelet
    - /etc/kubernetes
    - /etc/kube-proxy

- name: 安装程序
  copy:
    src: "{{ node_pkg_dir }}/{{ item }}"
    dest: /usr/local/bin/
    mode: "0755"
  with_items:
    - kubelet
    - kube-proxy

- name: 检查 cni-plugins 是否已经部署
  find:
    paths:
      - /opt/cni/bin/
  register: cniFilesFound

- name: 安装 cni-plugins
  unarchive:
    src: '{{ pkgs_dir }}/cni-plugins-linux-amd64-{{ cni_plugins_version }}.tgz'
    dest: /opt/cni/bin/
  when: cniFilesFound.matched <= 0

- name: 生成 /etc/cni/net.d/99-loopback.conf
  template:
    src: 99-loopback.conf.j2
    dest: /etc/cni/net.d/99-loopback.conf
    owner: root
    group: root
    mode: '0644'

- name: 复制配置文件
  copy:
    src: "{{ config_dir }}/{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: ca.pem, dest: /etc/kubernetes/ }
    - { src: "{{ inventory_hostname }}-key.pem", dest: /etc/kubelet/ }
    - { src: "{{ inventory_hostname }}.pem", dest: /etc/kubelet/ }
    - { src: "kubelet-{{ inventory_hostname }}.kubeconfig", dest: /etc/kubelet/kubeconfig }
    - { src: kube-proxy.kubeconfig, dest: /etc/kube-proxy/kubeconfig }

- name: 生成 /etc/kubelet/kubelet-config.yaml
  template:
    src: kubelet-config.yaml.j2
    dest: /etc/kubelet/kubelet-config.yaml
    owner: root
    group: root
    mode: "0644"

- name: 生成 /etc/kube-proxy/kube-proxy-config.yaml
  template:
    src: kube-proxy-config.yaml.j2
    dest: /etc/kube-proxy/kube-proxy-config.yaml
    owner: root
    group: root
    mode: '0644'

- name: 生成 /etc/systemd/system/kube-proxy.service
  template:
    src: kube-proxy.service.j2
    dest: /etc/systemd/system/kube-proxy.service
    owner: root
    group: root
    mode: '0644'

- import_tasks: runtime_containerd.yml
  when: container_runtime == "containerd"

- import_tasks: runtime_docker.yml
  when: container_runtime == "docker"

- name: systemctl daemon-reload
  systemd:
    daemon_reload: yes

- name: 启动 kubelet
  systemd:
    name: kubelet
    state: started
    enabled: yes

- name: 启动 kube-proxy
  systemd:
    name: kube-proxy
    state: started
    enabled: yes
