---
# TODO: 安装 docker ?

- name: 生成 /etc/systemd/system/kubelet.service
  template:
    src: kubelet-with-docker.service.j2
    dest: /etc/systemd/system/kubelet.service
    owner: root
    group: root
    mode: '0644'

- name: 启动 docker
  systemd:
    name: docker
    state: started
    enabled: yes
