- hosts: nodes
  become: true

  pre_tasks:

  - name: set hostname to {{inventory_hostname}}
    hostname:
      name: "{{ inventory_hostname }}"

  - name: 禁用 selinux
    selinux:
      state: disabled

  - name: update centos
    yum:
      name: '*'
      state: latest

  roles:
  - epel-repository
  - basic
  # - runc # or
  - docker
  - kfs-node
