- hosts: masters
  become: true

  vars:
    - k8s_version: "v1.17.4"
    - master_bins:
      - kubectl
      - kube-apiserver
      - kube-scheduler
      - kube-controller-manager
    - etcd_version: "v3.4.5"
    - etcd_internal_ip: "192.168.31.10"
    - kube_apiserver_ip: "192.168.31.10"

  pre_tasks:

  - name: set hostname to {{inventory_hostname}}
    hostname:
      name: "{{ inventory_hostname }}"

  - name: 禁用 selinux
    selinux:
      state: disabled

  - name: update centos
    yum:
      name: '*'
      state: latest

  roles:
  - epel-repository
  - basic
  - kfs-master
