- hosts: nodes
  become: true
  vars:
    kfslab_dir: "~/data/poeticloud/lab/devops/deploy/envs/k8s-3/kfslab"
    kfslab_node_dir: "{{ kfslab_dir }}/install/node"

  tasks:

  - name: 当前路径
    command: echo "{{ playbook_dir }}"

  # - debug:
  #     var: playbook_dir,inventory_dir
  # - debug:
  #     # var: playbook_dir,inventory_dir
  #     msg:
  #     - System {{ inventory_hostname }} has uuid {{ ansible_product_uuid }}
  #     - ansible_search_path = {{ ansible_search_path }}
  #     - inventory_hostname = {{ inventory_hostname }}
  #   when: "ansible_facts['os_family'] == 'RedHat'"
  # # Example that prints return information from the previous task
  # - shell: /usr/bin/uptime
  #   register: result

  # - debug:
  #     var: result
  #     verbosity: 1

  - name: Your copy task
    copy: src={{ item.src }} dest={{ item.dest }} mode={{ item.mode }}
    with_items:
      - { src: '{{ kfslab_node_dir }}/bin/', dest: '/usr/local/bin/', mode: "0755" }
